### ISSUE TITLE
datetime in filters

### ISSUE THREAD

**Issue by honzajavorek** [martinrusev/imbox#14]
`date__gt` and `date__lt` should accept `datetime.datetime` or `datetime.date` objects

**Comment by sblondon** [comment]
The current version in pypi.python.org accepts `Date` objects for  `date__gt` and `date__lt` but this issue is still open.

Implementation starts at https://github.com/martinrusev/imbox/blob/master/imbox/query.py#L23

Does it need more work ? Can it be closed ?

It would be nice to update the README to show this usage. I can do a pull-request for that.

**Comment by martinrusev** [comment]
@sblondon I think it can be closed with an explanation in the readme

**Comment by sblondon** [comment]
So the issue can be closed now?
